export const Iconografia = {
    categorias: [
        { nombre: "Autenticidad", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/4real.webp", clave: "fourreal" },
        { nombre: "Garantía", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/corazon.webp", clave: "corazon" },
        { nombre: "Tendencia", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/tendencia.webp", clave: "tendencia" },
        { nombre: "Iconico", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/icon.webp", clave: "icon" },
        { nombre: "Nuevo", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/new.webp", clave: "newIcon" },
        { nombre: "Memorable", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/estrellas.webp", clave: "estrellas" },
        { nombre: "Calidad", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/calidad.webp", clave: "calidad" },
        { nombre: "Residente", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/Residente.webp", clave: "residente" },
        { nombre: "Calidad Precio", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/calidad-precio.webp", clave: "calidadPrecio" },
    ],
    ocasiones: [
        { nombre: "Desayunos", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/desayunos.webp", clave: "desayunos" },
        { nombre: "Amigos", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/amigos.webp", clave: "amigos" },
        { nombre: "Cumpleaños", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/cumpleaños.webp", clave: "cumpleaños" },
        { nombre: "Night", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/noche.webp", clave: "noche" },
        { nombre: "Familiar", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/familiar.webp", clave: "familiar" },
        { nombre: "Negocios", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/negocios.webp", clave: "negocios" },
        { nombre: "Antojo", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/yum.webp", clave: "yum" },
        { nombre: "En pareja", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/en-pareja.webp", clave: "enPareja" },
        { nombre: "Munch", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/munch.webp", clave: "munch" },
    ],
    zonas: [
        { nombre: "Monterrey", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/mty.webp", clave: "mty" },
        { nombre: "Santa Catarina", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/sta.webp", clave: "sta" },
        { nombre: "Apodaca", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/apo.webp", clave: "apo" },
        { nombre: "Poniente", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/mty-pte.webp", clave: "mtyPte" },
        { nombre: "San Pedro", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/spg.webp", clave: "spg" },
        { nombre: "Escobedo", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/esc.webp", clave: "esc" },
        { nombre: "Sur", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/mty-sur.webp", clave: "mtySur" },
        { nombre: "Guadalupe", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/gpe.webp", clave: "gpe" },
        { nombre: "San Nicolás", icono: "https://residente.mx/fotos/fotos-estaticas/componente-iconos/snn.webp", clave: "snn" },
    ]
};